train:
  seed: 1
  torch_deterministic: True
  device: cpu
  total_timesteps: 100_000_000
  learning_rate: 2.5e-4
  num_envs: 6
  num_steps: 128
  anneal_lr: True
  gamma: 0.998
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 3
  norm_adv: True
  clip_coef: 0.1
  clip_vloss: True
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: ~

  env_pool_batch_size: 24
  envs_per_worker: 1
  envs_per_batch: ~
  env_pool: True
  verbose: True
  data_dir: experiments
  checkpoint_interval: 200
  cpu_offload: True
  pool_kernel: [0]
  batch_size: 32768
  batch_rows: 128
  bptt_horizon: 8
  vf_clip_coef: 0.1
  compile: False

sweep:
  method: random
  name: sweep
  metric:
    goal: maximize
    name: episodic_return
  # Nested parameters name required by WandB API
  parameters:
    train:
      parameters:
        learning_rate: {
          'distribution': 'log_uniform_values',
          'min': 1e-4,
          'max': 1e-1,
        }
        batch_size: {
          'values': [128, 256, 512, 1024, 2048],
        }
        batch_rows: {
          'values': [16, 32, 64, 128, 256],
        }
        bptt_horizon: {
          'values': [4, 8, 16, 32],
        }

pokemon_red:
  package: pokemon_red
  train:
    total_timesteps: 100_000_000_000
    num_envs: 1
    envs_per_worker: 1
    envs_per_batch: 1
    update_epochs: 3 # epoch sps 3, 4==no change; 8==1500; 16==1000
    gamma: 0.998
    batch_size: 16
    batch_rows: 4
    bptt_horizon: 2
    compile: False

pokemon-red:
  package: pokemon_red
pokemonred:
  package: pokemon_red
pokemon:
  package: pokemon_red
